### PR TITLE
Added a 3d printable case

### PR DESCRIPTION
**Pull request by earlthesquirrel**
These are the files for the 3d printable case.

### CODE REVIEW

**Comment by hanshuebner** [comment]
Nice!  I have a question, though:  What is the difference between Cover2.stl and TerminalBox.stl?  They look the same, but maybe I'm missing something?  A comment as to what the difference is would be nice.

**Comment by earlthesquirrel** [comment]
Whoops!  Wrong names...

Cover 1 is the Terminal Box
Terminal Box is Cover 1.

Cover 2 is named correctly.

I have NO idea how the names got transposed.

**Comment by earlthesquirrel** [comment]
Just pushed the right naming.

**Comment by hanshuebner** [comment]
The case looks good and fits the PCB well.  I wonder, however, how you intend the cover to be affixed to the body.  There seem to be no snap-fit hooks or anything.  Are you using Fusion360 for modeling?  There is a nice tutorial on how to do snap-fit lids here:  https://www.youtube.com/watch?v=VVmOtM60VWw

Maybe I'm missing something?

**Comment by earlthesquirrel** [comment]
The "catches" on the sides of the top do actually catch -- friction (and it
fits tight)  I wasn't
trying to "lock" the top on... It could be an enhancement (sinceI wasn't
designing it to be upside down :- )

I was playing with trying to keep the inside walls smooth, prevent them
from getting too thick, etc.
and didn't want to add a lip because it would allow the PCB in general
"slide around".
I'd have to thicken the walls and add notches, etc. for them.  All could be
done.
All a time/effort/speed set of tradeoffs.

I'm not using Fusion360, I've got other tools...

I could do additional work... will have to think on it.
How many of these boards are you selling?

Have you printed out one yet?

Earl

**Comment by hanshuebner** [comment]
Hi Earl,

I've printed the case on my Prusa i3 MK3 using generic PLA filament, see the photo in my previous comment.  The lid does not stick to the body at all.

I have just built the terminal for myself.  As usual, I have a few more PCBs and might sell them, but that'd be only for my amusement.  Maybe I'll just pass on the PCB and the programmed controllers.

Cheers, Hans

**Comment by earlthesquirrel** [comment]
Hmmm, I printed on my Stanley Model 1, and I can turn it upside down and
the top doesn't come off.  It has PLA in it right now as well.
(funny we both printed in blue :-) )

I have a previous one here and I can shake it the top doesn't come off
until I get pretty violent with the shaking.

I just did some looking at your picture  (it didn't come thru in the e-mail
thread so I was rather confused... I had to go to github directly to see
it... ) and maybe your printer just generated smoother surfaces.  That
could be it...

I will print another for a friend (who bought one of your boards here as
well.... ) and see if the size change made any difference.
When I have some time, I'll see about tweaking the catches to make it a
more "mechanical" vs friction fit.   I could go with rounder ends on the
ends of the existing legs on the top and then put dimples in the
insides.... that would give a better grab but not make it impossible to get
off.

But does it work ok as a case (aside from the top issue) for you?

Earl

**Comment by hanshuebner** [comment]
Hi Earl,

no worries, I'll just tape the two parts together.  It won't look as nice, but it'll be much better than the bare PCB.  I have some plans to redesign the PCB to include a RS232 level converter on the board, but it is not a high priority project at this time, so for now, your case will do just fine :)

Note that I'm not the author of the terminal code or the original code, but just a user.

-Hans

**Comment by earlthesquirrel** [comment]
You could always put super glue on the legs...  if you don't want to open it easily :-)

**Pull request merged**
