### PR TITLE
Swedish keyboard layout

### PR DESCRIPTION
**Pull request by steka**
* Add Swedish keyboard layout (SE).
* Clean up compilations warnings (the deprecated PLIB warnings are only suppressed, so that more important warnings are easier spotted).
* Change source encoding from ISO 8859-1 to UTF-8 to avoid messing up terminal_keyboard.c
* Remove (and added to .gitignore) the generated files in the nbproject folder.

### CODE REVIEW

**Comment by petrohi** [comment]
Looks great!

Do you mind adding your name to the copyright notice shown on the startup screen?

**Comment by steka** [comment]
Hmmm....strange...?!?!
I didn't remove `.generated_files`, it was already ignored before.
Also, I just tested with a `git clean -x -d -f`, and rebuilt the new master branch and it compiled without problems (and created `.generated_files`).

**Comment by steka** [comment]
I have now even tried to make a new clean clone of https://github.com/petrohi/terminal.git
[Commit hash: 8f1ba8c451b27a6a828bf8803b4c062f9a199cc1]
 and that also builds without problem.

I'm using MPLAB X IDE v5.45 and XC32 v2.50, and building by pressing the F11-key.
What do you have, and how do you build?

**Comment by petrohi** [comment]
Reloaded MPLAB and now it works!

**Pull request merged**
